### ISSUE TITLE
Ign-delays referenced before assignment

### ISSUE THREAD

**Issue by morganmayer** [pr-omethe-us/PyTeCK#13]
This model works with the Burcat ChemKED files, however does not work for other ChemKED files I try to use individually such as data from Davidson, Hartmann, Mittal and Sung, and Shen.  All of them are validated with ChemKED 0.4.1. The error says " 'ign-delays' referenced before assignment". 

[test_performance_toluene_onefile.zip](https://github.com/pr-omethe-us/PyTeCK/files/2917237/test_performance_toluene_onefile.zip)

**Comment by morganmayer** [comment]
When running PyTeCK v0.2.5a5 with a ChemKED file that has an ignition delay definition of "d/dt max extrapolated" I get this error message: "pint.errors.DimensionalityError: Cannot convert from 'second' to 'dimensionless' ". This would be with the Davidson files and Shen files. @kyleniemeyer

**Comment by kyleniemeyer** [comment]
Got it. I will work on fixing this.

**Comment by kyleniemeyer** [comment]
@morganmayer can you let me know which line(s) it says this error occurred at?

**Comment by kyleniemeyer** [comment]
Getting this error message, even after the recent fixes:
```
.../site-packages/pyteck/eval_model.py:169: RuntimeWarning: Warning: multiple changing variables. Using temperature.
  RuntimeWarning
Traceback (most recent call last):
  File "test_performance.py", line 40, in <module>
    skip_validation=True
  File ".../site-packages/pyteck/eval_model.py", line 375, in evaluate_model
    sim.process_results()
  File ".../site-packages/pyteck/simulation.py", line 502, in process_results
    if len(ign_delays) > 0:
UnboundLocalError: local variable 'ign_delays' referenced before assignment
```

**Comment by kyleniemeyer** [comment]
Correction, it seems this was actually fixed with the recent changes.
